volumes:
  qdrant_data:

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_local
    restart: always
    ports: 
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage